### ISSUE TITLE
Error: jsonwebtoken not found

### ISSUE THREAD

**Issue by coooolers** [fiction-com/factor#15]
When I run yarn factor dev, I get this error

  ✔ Installing Dependencies [Done!]
  ✔ Creating Extension Loaders [Done!]
(node:14870) UnhandledPromiseRejectionWarning: Error: Cannot find module 'jsonwebtoken'

**Comment by arpowers** [comment]
this was patched, let me push a new release.

**Comment by coooolers** [comment]
ok thx. Could you pl. add instructions where to specify the db connection string and smtp details? Also I think git clone <this-repository> is missing in the docs.

**Comment by arpowers** [comment]
@coooolers definitely, we are still in pre-alpha and both the setup process and docs need some love.. working on it now.

**Comment by coooolers** [comment]
Okay.. thank you for the response.
