### ISSUE TITLE
create-factor-app won't run in Firefox

### ISSUE THREAD

**Issue by Twitch0125** [fiction-com/factor#89]
I tried both NPX and the Yarn method of create-factor-app. I don't receive any errors from the server. I receive these errors in the console:
![firefox-errors](https://user-images.githubusercontent.com/44715857/69001530-97ecfd00-089d-11ea-8eb0-8cafaa5399a2.png)

**Steps to Reproduce**
`yarn create factor-app factorApp`
`yarn factor dev`
visit localhost:3000 in Firefox (v.70.0.1)
app seems to load for a split second and then I get the image above

I've only tested on Linux (OpenSUSE Tumbleweed and PeppermintOS)

**Comment by arpowers** [comment]
@Twitch0125  did you try running this in your terminal?  It's an NPM scaffolding utility.

<img width="640" alt="Screen Shot 2019-11-18 at 11 25 37 AM" src="https://user-images.githubusercontent.com/308134/69044990-38eecb80-09f6-11ea-8f18-1dd23ebed421.png">

**Comment by Twitch0125** [comment]
I tried both the Yarn method and the NPX method and get the same results each time. I can visit the app on chrome/chromium however without any issues, its just with firefox I get issues.

**Comment by arpowers** [comment]
Oh I see, ok I'll take a look. Sometimes SSR and Firefox can be finicky as any time the server rendered HTML and the browser rendered HTML are slightly different, it throws this error.

**Comment by arpowers** [comment]
@Twitch0125 after some looking, it appears to be a difference/bug in Firefox's handling of arrays vs V8 which runs in Node and Webkit/Chrome.  I'll investigate further.

**Comment by arpowers** [comment]
fixed in latest release.
